// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hatimonline.code.roosec.domain;

import java.lang.String;

privileged aspect SystemUserGroup_Roo_JavaBean {
    
    public String SystemUserGroup.getGroupName() {
        return this.groupName;
    }
    
    public void SystemUserGroup.setGroupName(String groupName) {
        this.groupName = groupName;
    }
    
}
