// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hatimonline.code.roosec.domain;

import java.lang.String;

privileged aspect SystemUser_Roo_JavaBean {
    
    public void SystemUser.setUsername(String username) {
        this.username = username;
    }
    
    public void SystemUser.setPassword(String password) {
        this.password = password;
    }
    
}
