// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hatimonline.code.roosec.domain;

import com.hatimonline.code.roosec.domain.SystemUserGroupDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SystemUserGroupIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SystemUserGroupIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SystemUserGroupIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: SystemUserGroupIntegrationTest: @Transactional;
    
    @Autowired
    private SystemUserGroupDataOnDemand SystemUserGroupIntegrationTest.dod;
    
    @Test
    public void SystemUserGroupIntegrationTest.testCountSystemUserGroups() {
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUserGroup' failed to initialize correctly", dod.getRandomSystemUserGroup());
        long count = com.hatimonline.code.roosec.domain.SystemUserGroup.countSystemUserGroups();
        org.junit.Assert.assertTrue("Counter for 'SystemUserGroup' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SystemUserGroupIntegrationTest.testFindSystemUserGroup() {
        com.hatimonline.code.roosec.domain.SystemUserGroup obj = dod.getRandomSystemUserGroup();
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUserGroup' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUserGroup' failed to provide an identifier", id);
        obj = com.hatimonline.code.roosec.domain.SystemUserGroup.findSystemUserGroup(id);
        org.junit.Assert.assertNotNull("Find method for 'SystemUserGroup' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'SystemUserGroup' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SystemUserGroupIntegrationTest.testFindAllSystemUserGroups() {
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUserGroup' failed to initialize correctly", dod.getRandomSystemUserGroup());
        long count = com.hatimonline.code.roosec.domain.SystemUserGroup.countSystemUserGroups();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'SystemUserGroup', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.hatimonline.code.roosec.domain.SystemUserGroup> result = com.hatimonline.code.roosec.domain.SystemUserGroup.findAllSystemUserGroups();
        org.junit.Assert.assertNotNull("Find all method for 'SystemUserGroup' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'SystemUserGroup' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SystemUserGroupIntegrationTest.testFindSystemUserGroupEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUserGroup' failed to initialize correctly", dod.getRandomSystemUserGroup());
        long count = com.hatimonline.code.roosec.domain.SystemUserGroup.countSystemUserGroups();
        if (count > 20) count = 20;
        java.util.List<com.hatimonline.code.roosec.domain.SystemUserGroup> result = com.hatimonline.code.roosec.domain.SystemUserGroup.findSystemUserGroupEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'SystemUserGroup' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'SystemUserGroup' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SystemUserGroupIntegrationTest.testFlush() {
        com.hatimonline.code.roosec.domain.SystemUserGroup obj = dod.getRandomSystemUserGroup();
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUserGroup' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUserGroup' failed to provide an identifier", id);
        obj = com.hatimonline.code.roosec.domain.SystemUserGroup.findSystemUserGroup(id);
        org.junit.Assert.assertNotNull("Find method for 'SystemUserGroup' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySystemUserGroup(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'SystemUserGroup' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SystemUserGroupIntegrationTest.testMerge() {
        com.hatimonline.code.roosec.domain.SystemUserGroup obj = dod.getRandomSystemUserGroup();
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUserGroup' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUserGroup' failed to provide an identifier", id);
        obj = com.hatimonline.code.roosec.domain.SystemUserGroup.findSystemUserGroup(id);
        boolean modified =  dod.modifySystemUserGroup(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.hatimonline.code.roosec.domain.SystemUserGroup merged = (com.hatimonline.code.roosec.domain.SystemUserGroup) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'SystemUserGroup' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SystemUserGroupIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUserGroup' failed to initialize correctly", dod.getRandomSystemUserGroup());
        com.hatimonline.code.roosec.domain.SystemUserGroup obj = dod.getNewTransientSystemUserGroup(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUserGroup' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'SystemUserGroup' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'SystemUserGroup' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SystemUserGroupIntegrationTest.testRemove() {
        com.hatimonline.code.roosec.domain.SystemUserGroup obj = dod.getRandomSystemUserGroup();
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUserGroup' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUserGroup' failed to provide an identifier", id);
        obj = com.hatimonline.code.roosec.domain.SystemUserGroup.findSystemUserGroup(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'SystemUserGroup' with identifier '" + id + "'", com.hatimonline.code.roosec.domain.SystemUserGroup.findSystemUserGroup(id));
    }
    
}
