// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hatimonline.code.roosec.domain;

import com.hatimonline.code.roosec.domain.SystemUserDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SystemUserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SystemUserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SystemUserIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: SystemUserIntegrationTest: @Transactional;
    
    @Autowired
    private SystemUserDataOnDemand SystemUserIntegrationTest.dod;
    
    @Test
    public void SystemUserIntegrationTest.testCountSystemUsers() {
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUser' failed to initialize correctly", dod.getRandomSystemUser());
        long count = com.hatimonline.code.roosec.domain.SystemUser.countSystemUsers();
        org.junit.Assert.assertTrue("Counter for 'SystemUser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SystemUserIntegrationTest.testFindSystemUser() {
        com.hatimonline.code.roosec.domain.SystemUser obj = dod.getRandomSystemUser();
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUser' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUser' failed to provide an identifier", id);
        obj = com.hatimonline.code.roosec.domain.SystemUser.findSystemUser(id);
        org.junit.Assert.assertNotNull("Find method for 'SystemUser' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'SystemUser' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SystemUserIntegrationTest.testFindAllSystemUsers() {
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUser' failed to initialize correctly", dod.getRandomSystemUser());
        long count = com.hatimonline.code.roosec.domain.SystemUser.countSystemUsers();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'SystemUser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.hatimonline.code.roosec.domain.SystemUser> result = com.hatimonline.code.roosec.domain.SystemUser.findAllSystemUsers();
        org.junit.Assert.assertNotNull("Find all method for 'SystemUser' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'SystemUser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SystemUserIntegrationTest.testFindSystemUserEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUser' failed to initialize correctly", dod.getRandomSystemUser());
        long count = com.hatimonline.code.roosec.domain.SystemUser.countSystemUsers();
        if (count > 20) count = 20;
        java.util.List<com.hatimonline.code.roosec.domain.SystemUser> result = com.hatimonline.code.roosec.domain.SystemUser.findSystemUserEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'SystemUser' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'SystemUser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SystemUserIntegrationTest.testFlush() {
        com.hatimonline.code.roosec.domain.SystemUser obj = dod.getRandomSystemUser();
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUser' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUser' failed to provide an identifier", id);
        obj = com.hatimonline.code.roosec.domain.SystemUser.findSystemUser(id);
        org.junit.Assert.assertNotNull("Find method for 'SystemUser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySystemUser(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'SystemUser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SystemUserIntegrationTest.testMerge() {
        com.hatimonline.code.roosec.domain.SystemUser obj = dod.getRandomSystemUser();
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUser' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUser' failed to provide an identifier", id);
        obj = com.hatimonline.code.roosec.domain.SystemUser.findSystemUser(id);
        boolean modified =  dod.modifySystemUser(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.hatimonline.code.roosec.domain.SystemUser merged = (com.hatimonline.code.roosec.domain.SystemUser) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'SystemUser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SystemUserIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUser' failed to initialize correctly", dod.getRandomSystemUser());
        com.hatimonline.code.roosec.domain.SystemUser obj = dod.getNewTransientSystemUser(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUser' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'SystemUser' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'SystemUser' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SystemUserIntegrationTest.testRemove() {
        com.hatimonline.code.roosec.domain.SystemUser obj = dod.getRandomSystemUser();
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUser' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'SystemUser' failed to provide an identifier", id);
        obj = com.hatimonline.code.roosec.domain.SystemUser.findSystemUser(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'SystemUser' with identifier '" + id + "'", com.hatimonline.code.roosec.domain.SystemUser.findSystemUser(id));
    }
    
}
